# Copyright (C) 2024 IOTech Ltd
# SPDX-License-Identifier: Apache-2.0

"""
The autoevent module of the App Functions SDK Python package.

This module defines the AutoEvent class which represents an auto event in the context of the App
Functions SDK. An auto event is a scheduled event that is generated by a device.

Classes:
    AutoEvent: Represents an auto event. It has attributes like interval, on_change, and
    source_name.
"""

from dataclasses import dataclass


# pylint: disable=invalid-name
@dataclass
class AutoEvent:
    """
    Represents an auto event.

    An auto event is a scheduled event that is generated by a device. It has attributes like
    interval, on_change, and source_name.

    Attributes:
        interval (str): The interval at which the event is generated.
        onChange (bool): Whether the event is generated only when the device state changes.
        sourceName (str): The name of the source that generates the event.
    """
    interval: str
    onChange: bool
    sourceName: str
